from tkinter import *   #ASSIM QUE CHAMA A BIBLIOTECA 

janela = Tk()   #USANDO UMA VARIAVEL PARA SER A JANELA PRINCIPAL


janela.geometry("400x400")  #DEFININDO DIMENSÕES DA JANELA
janela.mainloop()   #COMANDO PARA RODAR A JANELA E APARECER NA TELA